# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "rake", "~>10.0.0"
gem "diffy", "~>2.0.9"

gem "rdoc", "~>3.10", :group => [:development, :test]
gem "hoe", "~>3.5", :group => [:development, :test]

# vim: syntax=ruby
